version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22 # or 20 if supported
    commands:
      - echo "Installing dependencies..."
      - npm ci # clean install for reproducible builds

  build:
    commands:
      - echo "Building Vite React app..."
      - npm run build
      - echo "Build completed successfully."

artifacts:
  files:
    - "**/*"
  base-directory: dist
  discard-paths: no
